DataValidation:
  drift_threshold: 0.05

DataTransformation:
  test_size: 0.25
  random_state: 42
  stratify_column: quality
  feature_scaling:
    method: standard
    save_scaler_path: artifacts/data_transformation/scaler.joblib

ElasticNet:
  alpha: 0.2
  l1_ratio: 0.1
